apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: final
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306