apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data
  namespace: final
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
  labels:
    app: sql-data
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: sql-data
