AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECRImagePullPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
            Resource: '*'

  EKSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'EKS-ECR-Image-Pull-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'eks.amazonaws.com'
            Action: 'sts:AssumeRole'

  AttachECRPolicy:
    Type: 'AWS::IAM::PolicyAttachment'
    Properties:
      PolicyArn: !Ref ECRImagePullPolicy
      Groups: []
      Roles:
        - !Ref EKSRole
